/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thanosviagens;

import java.awt.Font;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Welerson Melo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldBuscaCidade = new javax.swing.JTextField();
        btBuscaCidade = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelAnswerCidade = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cbMediaServico = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cbPiscina = new javax.swing.JCheckBox();
        cbRestaurante = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelAnswerAll = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        textFieldBuscaCidadesFranquia = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        labelAnswerComentarios = new javax.swing.JTextArea();
        btPesquisaFranquiaCidade = new javax.swing.JButton();
        cbEstacionamento = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        labelAnswerCidadesFranquia = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemNumFranquias = new javax.swing.JMenuItem();
        menuItemMelhoresFranquias = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemUsuariosAtual = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanos Viagens");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel1.setText("Thanos Viagens - Suas viagens pela metade do preço");
        jLabel1.setMaximumSize(new java.awt.Dimension(305, 27));

        jLabel2.setText("Pesquisa por Hoteis em uma cidade:");

        textFieldBuscaCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textFieldBuscaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscaCidadeActionPerformed(evt);
            }
        });

        btBuscaCidade.setText("Pesquisar");
        btBuscaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaCidadeActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        labelAnswerCidade.setEditable(false);
        labelAnswerCidade.setColumns(20);
        labelAnswerCidade.setRows(5);
        labelAnswerCidade.setDisabledTextColor(new java.awt.Color(5, 5, 5));
        labelAnswerCidade.setEnabled(false);
        labelAnswerCidade.setFocusable(false);
        jScrollPane1.setViewportView(labelAnswerCidade);

        jButton1.setText("Ver todos os hoteis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbMediaServico.setText("Média Serviço > 6");
        cbMediaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMediaServicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Pesquise todos os hoteis com alguns filtros");

        cbPiscina.setText("Piscina");
        cbPiscina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPiscinaActionPerformed(evt);
            }
        });

        cbRestaurante.setText("Restaurante");
        cbRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRestauranteActionPerformed(evt);
            }
        });

        jScrollPane2.setEnabled(false);

        labelAnswerAll.setEditable(false);
        labelAnswerAll.setColumns(20);
        labelAnswerAll.setRows(5);
        labelAnswerAll.setDisabledTextColor(new java.awt.Color(5, 5, 5));
        labelAnswerAll.setEnabled(false);
        labelAnswerAll.setFocusable(false);
        jScrollPane2.setViewportView(labelAnswerAll);

        jLabel4.setText("Pesquise em quais cidades está uma franquia:");

        textFieldBuscaCidadesFranquia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textFieldBuscaCidadesFranquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscaCidadesFranquiaActionPerformed(evt);
            }
        });

        jScrollPane3.setEnabled(false);

        labelAnswerComentarios.setEditable(false);
        labelAnswerComentarios.setColumns(20);
        labelAnswerComentarios.setRows(5);
        labelAnswerComentarios.setDisabledTextColor(new java.awt.Color(5, 5, 5));
        labelAnswerComentarios.setEnabled(false);
        labelAnswerComentarios.setFocusable(false);
        jScrollPane3.setViewportView(labelAnswerComentarios);

        btPesquisaFranquiaCidade.setText("Pesquisar");
        btPesquisaFranquiaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaFranquiaCidadeActionPerformed(evt);
            }
        });

        cbEstacionamento.setText("Estacionamento");

        jScrollPane4.setEnabled(false);

        labelAnswerCidadesFranquia.setEditable(false);
        labelAnswerCidadesFranquia.setColumns(20);
        labelAnswerCidadesFranquia.setRows(5);
        labelAnswerCidadesFranquia.setDisabledTextColor(new java.awt.Color(5, 5, 5));
        labelAnswerCidadesFranquia.setEnabled(false);
        labelAnswerCidadesFranquia.setFocusable(false);
        jScrollPane4.setViewportView(labelAnswerCidadesFranquia);

        jLabel5.setText("Comentários sobre hosperarias");

        jMenu1.setText("Opções do Gerente");

        menuItemNumFranquias.setText("Ver Número Franquias por Hotel");
        menuItemNumFranquias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNumFranquiasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemNumFranquias);

        menuItemMelhoresFranquias.setText("Melhores Franquias por Média Geral");
        menuItemMelhoresFranquias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMelhoresFranquiasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemMelhoresFranquias);

        jMenuItemUsuarios.setText("Histórico de Reserva por Usuário");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarios);

        jMenuItemUsuariosAtual.setText("Usuários hospedado hoje");
        jMenuItemUsuariosAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosAtualActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuariosAtual);

        jMenuItem1.setText("Usuários que fizeram reserva em um tipo de quarto com duas camas ou mais do mesmo tipo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscaCidade))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPiscina)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbEstacionamento)
                                            .addComponent(cbRestaurante))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMediaServico)
                                        .addGap(46, 46, 46)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldBuscaCidadesFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPesquisaFranquiaCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(224, 224, 224))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(769, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(134, 134, 134)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaCidade)
                    .addComponent(jButton1)
                    .addComponent(textFieldBuscaCidadesFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisaFranquiaCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMediaServico)
                            .addComponent(cbEstacionamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPiscina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );

        jLabel1.getAccessibleContext().setAccessibleName("titulo");
        textFieldBuscaCidade.getAccessibleContext().setAccessibleName("buscaCidade");

        getAccessibleContext().setAccessibleName("main");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuscaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscaCidadeActionPerformed

    private void btBuscaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaCidadeActionPerformed
        String textBusca = textFieldBuscaCidade.getText().toString().trim();
        ConnectionDB con = new ConnectionDB();
        ArrayList<String> ansCon = new ArrayList<String>();
        
        String saida = "Hoteis encontrados em "+textBusca+":\n";
        
        try {
            ansCon = con.buscaPorCidade(textBusca);
            
            for(String ans : ansCon){
                saida += ans + "\n";
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro. Nenhum hotel nesta cidade!";
        }
        
        if(ansCon.isEmpty()) 
            saida += "Nenhum hotel nesta cidade!";
        labelAnswerCidade.setFont(new Font("Serif", Font.PLAIN, 15));
        labelAnswerCidade.setText(saida);
    }//GEN-LAST:event_btBuscaCidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnectionDB con = new ConnectionDB();
        ArrayList<String> ansCon = new ArrayList<String>();
        
        String saida = "Lista de Hoteis:\n";
        
        if(cbMediaServico.isSelected()) {
            try {
                ResultSet ansResult = con.buscaHoteisMediaServico();

                while(ansResult.next()){                           
                    double media = ansResult.getDouble(2);
                    media = (double) Math.round(media*100) / 100;
                    
                    saida += "Média: " + String.valueOf(media) + "\t" + ansResult.getString(1) + "\n";
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                saida += "Erro!";
            }
        } else {
            try {
                ansCon = con.buscaTodosHoteis(cbEstacionamento.isSelected(), cbRestaurante.isSelected(), cbPiscina.isSelected());

                for(String ans : ansCon){
                    saida += ans + "\n";
                }
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                saida += "Erro!";
            }
        }
        
        labelAnswerAll.setFont(new Font("Serif", Font.PLAIN, 15));
        labelAnswerAll.setText(saida);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbPiscinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPiscinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPiscinaActionPerformed

    private void cbRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRestauranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRestauranteActionPerformed

    private void menuItemNumFranquiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNumFranquiasActionPerformed
        ConnectionDB con = new ConnectionDB();
        
        String saida = "Quantidade de Franquias Por Hotel:\n";
        
        try {
            ResultSet result = con.buscaHotelPorFranquia();
            
            while(result.next()){
                String hotel = result.getString(1);
                long quantFranquias = result.getLong(2);
                
                saida += String.valueOf(quantFranquias) + " | " + hotel + "\n"; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        JOptionPane.showMessageDialog(rootPane, saida);
    }//GEN-LAST:event_menuItemNumFranquiasActionPerformed

    private void textFieldBuscaCidadesFranquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscaCidadesFranquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscaCidadesFranquiaActionPerformed

    private void btPesquisaFranquiaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaFranquiaCidadeActionPerformed
        String textBusca = textFieldBuscaCidadesFranquia.getText().toString().trim();
        ConnectionDB con = new ConnectionDB();
        ResultSet ansCon;
        
        String saida = "Hoteis encontrados e cidade correspondente :\n";
        
        try {
            ansCon = con.buscaCidadesHotel(textBusca);
            int cont = 0;
            
            while(ansCon.next()){
                saida += ansCon.getString(1) + " em ";
                saida += ansCon.getString(2) + "\n";
                cont++;
            }
            if(cont == 0){
                saida += "Não foram encontradas Franquias desse hotel";
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        labelAnswerComentarios.setFont(new Font("Serif", Font.PLAIN, 15));
        labelAnswerComentarios.setText(saida);
    }//GEN-LAST:event_btPesquisaFranquiaCidadeActionPerformed

    private void menuItemMelhoresFranquiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMelhoresFranquiasActionPerformed
        ConnectionDB con = new ConnectionDB();
        
        String saida = "Média Geral - Franquia:\n";
        
        try {
            ResultSet result = con.buscaMediaPorFranquia();
            
            while(result.next()){
                String hotel = result.getString(1);
                double media = result.getDouble(2);
                
                media = (double) Math.round(media*100) / 100;
                
                saida += String.valueOf(media) + "  -  " + hotel + "\n"; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        JOptionPane.showMessageDialog(rootPane, saida);
    }//GEN-LAST:event_menuItemMelhoresFranquiasActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        ConnectionDB con = new ConnectionDB();
        
        String saida = "Nome do Usuário - ID reserva:\n";
        
        try {
            ResultSet result = con.buscaUsuariosServa();
            
            while(result.next()){
                String usuario = result.getString(1);
                long id_reserva = result.getLong(2);
                
                saida += usuario + " : " + String.valueOf(id_reserva) + "\n"; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        JOptionPane.showMessageDialog(rootPane, saida);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void cbMediaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMediaServicoActionPerformed
        if(cbMediaServico.isSelected()){
            boolean cond = false;
            cbEstacionamento.setSelected(cond);
            cbPiscina.setSelected(cond);
            cbRestaurante.setSelected(cond);
            
            cbEstacionamento.setEnabled(cond);
            cbPiscina.setEnabled(cond);
            cbRestaurante.setEnabled(cond);
        } else {
            boolean cond = true;
            
            cbEstacionamento.setEnabled(cond);
            cbPiscina.setEnabled(cond);
            cbRestaurante.setEnabled(cond);
        }
        
        
    }//GEN-LAST:event_cbMediaServicoActionPerformed

    private void jMenuItemUsuariosAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosAtualActionPerformed
        ConnectionDB con = new ConnectionDB();
        
        String saida = "Data de Saída - Nome do Usuário:\n";
        
        try {
            ResultSet result = con.buscaUsuariosHospedadosNoMomento();
            
            while(result.next()){
                String usuario = result.getString(1);
                Date data = result.getDate(2);
                
                String dataSaida = new SimpleDateFormat("dd/MM/yyyy").format(data);
                        
                saida += "Data saída: "+ dataSaida + " - " + usuario + "\n"; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        JOptionPane.showMessageDialog(rootPane, saida);
    }//GEN-LAST:event_jMenuItemUsuariosAtualActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConnectionDB con = new ConnectionDB();
        
        String saida = "Nome do Usuário:\n";
        
        try {
            ResultSet result = con.buscaUsuarioEspecial();
            
            while(result.next()){
                String usuario = result.getString(1);
                
                saida += usuario + "\n"; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        JOptionPane.showMessageDialog(rootPane, saida);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(rootPane, "Bem vindo ao sistema Thanos. Encontre aqui o hotel ideal para você!");
        ConnectionDB con = new ConnectionDB();
        String saida = "Nome do Usuário - Comentários - Franquia:\n";
        
        try {
            ResultSet result = con.buscaComentarios();
            int cont = 1;
            while(result.next()){
                String usuario = result.getString(1);
                String comentario = result.getString(2);
                String franquia = result.getString(3);
                
                saida += String.valueOf(cont) + ". " + usuario + ": " + comentario + " sobre " + franquia +"\n"; 
                cont++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            saida += "Erro!";
        }
        
        labelAnswerComentarios.setText(saida);
    }//GEN-LAST:event_formWindowOpened

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscaCidade;
    private javax.swing.JButton btPesquisaFranquiaCidade;
    private javax.swing.JCheckBox cbEstacionamento;
    private javax.swing.JCheckBox cbMediaServico;
    private javax.swing.JCheckBox cbPiscina;
    private javax.swing.JCheckBox cbRestaurante;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenuItem jMenuItemUsuariosAtual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea labelAnswerAll;
    private javax.swing.JTextArea labelAnswerCidade;
    private javax.swing.JTextArea labelAnswerCidadesFranquia;
    private javax.swing.JTextArea labelAnswerComentarios;
    private javax.swing.JMenuItem menuItemMelhoresFranquias;
    private javax.swing.JMenuItem menuItemNumFranquias;
    private javax.swing.JTextField textFieldBuscaCidade;
    private javax.swing.JTextField textFieldBuscaCidadesFranquia;
    // End of variables declaration//GEN-END:variables
}
